### ISSUE TITLE
[Tracking] Documentation 2.0 migration

### ISSUE THREAD

**Issue by cloud-j-luna** [akash-network/support#86]
This issue serves the purpose of tracking the work needed to be done to migrate the old documentation to the new structure.

Outdated:
- https://docs.akash.network/providers/build-a-cloud-provider/akash-provider-checkup
- https://docs.akash.network/deploy/tls-termination-of-akash-deployments #2 #3 

Won't Migrate:
- https://docs.akash.network/other-resources/archived-resources/akash-v0.18.0-cli-release-notes
- https://docs.akash.network/other-resources/archived-resources/provider-upgrade

Enhancements:
- [x] Code syntax highlight
- [x] Tags and categories for pages

Acceptance Criteria:
- [x] New documentation website using Hugo
- [x] Support for localization
- [ ] Old documentation website archived
- [ ] New docs repository transferred to `akash-network` organization

This issue will be updated as we progress and find improvements to be made.

**Comment by aktdenis** [comment]
Luna, first of all thank you for your efforts. 
Here is my feedback: 
- favicon seems to be condensed, imo tab name should say: Akash Documentation, not Official Documentation. 
- i'm thinking if we should skip the hero image part and the button "start here", unless this plays a certain role for users. i would suggest we take the user directly to docs and avoid/skip this part where user has to click either "start here" or "documentation" 
- on the other hand the first page of docs should be visually appealing and it should spark interest in visitors/users. why not combine the page with big image and the first page of docs? - i'm sharing some design drafts at the end of this feedback. 
- overall design direction should follow the established and establishing design presence of Akash. This means we use certain typography, rules within typography, colors and imagery/illustrations. Keeping everything light and minimalistic will def. help. 
- any thoughts on adding existing libraries such as tailwind, radix ui, chakra, shadcn, bootstrap? it might help when the docs grow and other users would like to contribute. (was talking with front-end dev contributors for console and website and all prefer some sort of a library - meaning we shouldn't custom code everything)

**Comment by aktdenis** [comment]
<img width="1132" alt="Screenshot 2023-04-25 at 21 02 25" src="https://user-images.githubusercontent.com/116030971/234376967-fd1b64af-38da-4029-8d72-21528f8c69b1.png">

**Comment by aktdenis** [comment]
Here are couple of drafts for the starting page. Also providing an example of content page, to get a feeling of typography treatment, breaks, links etc. 

![akash-docs](https://user-images.githubusercontent.com/116030971/234377157-8555cab4-4052-4789-9391-75f27c77e683.png)

![akash-docs-1](https://user-images.githubusercontent.com/116030971/234377154-2434ce86-cb9f-40d2-a9d8-bdaa2f0d87a7.png)
![akash-docs-3](https://user-images.githubusercontent.com/116030971/234377147-9da553a0-acd2-4bd2-90d7-902082e83962.png)
![akash-docs-2](https://user-images.githubusercontent.com/116030971/234377150-6e35adaa-fd5d-4bf9-bd3a-cb13dfb6602c.png)

**Comment by aktdenis** [comment]
hey @Andree37 , great! i'm sharing the figma drafts here: https://www.figma.com/file/S63tyfwHvDJ9CuDeYrK8k8/akash-docs?node-id=48%3A2666&t=vyQJTtDAusynoKBA-1

please let me know if you need anything else, here to support you.👋🏼

**Comment by aktdenis** [comment]
One more thing we discussed in one of our docs meetings. Would be great to be able to copy code snippets with a single click. 

Code example:
https://codepen.io/foxbeefly/pen/dyWbQgJ

Live example: 
https://fly.io/docs/apps/deploy/

**Comment by cloud-j-luna** [comment]
Hey @aktdenis that is already implemented and available on the development version 😄
